# These are supported funding model platforms

github: []
patreon:
open_collective:
ko_fi: eliasbenb
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom: ["paypal.me/eliasbenb", "bitcoin:bc1qxs4hmwcs0vnkkf073rng6lywfmk9wzr2xgf7l729h2es8cst7f2qyvgu0e?message=main&time=1617268041"]
